# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:

    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/default'

        remotedocs.storage:
            adapter: 'aws'
            options:
                client: Aws\S3\S3Client # The service ID of the Aws\S3\S3Client instance
                bucket: '%env(AWS_S3_BUCKET_NAME)%'

                prefix: '%env(AWS_S3_DOCS_PREFIX)%'