twig:
    default_path: '%kernel.project_dir%/templates'


    form_themes: 
        - 'bootstrap_4_layout.html.twig'
        # 'form/layout.html.twig'
        # 'form/fields.html.twig'


    globals:
        app_name: '%env(APP_NAME)%'

        aws_s3_bucket_name: '%env(AWS_S3_BUCKET_NAME)%'
        
