vich_uploader:
    db_driver: orm
    storage: flysystem

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    mappings:

        local_user_docs:
            uri_prefix: /DOCS/user_docs
            # para la url
            upload_destination: DOCS/user_docs
            # para el almacenaje en el servidor
            
            namer: Vich\UploaderBundle\Naming\OrignameNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true


        remote_user_docs:
            uri_prefix: /DOCS/user_docs
            upload_destination: remotedocs.storage

            namer: Vich\UploaderBundle\Naming\OrignameNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true


